INSTALL PLUGIN INNODB SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_TRX SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_LOCKS SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_LOCK_WAITS SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_CMP SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_CMP_RESET SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_CMPMEM SONAME 'ha_innodb.so';
INSTALL PLUGIN INNODB_CMPMEM_RESET SONAME 'ha_innodb.so';



INSTALL PLUGIN INNODB SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_TRX SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_LOCKS SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_LOCK_WAITS SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_CMP SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_CMP_RESET SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_CMPMEM SONAME 'ha_innodb_plugin.so';
INSTALL PLUGIN INNODB_CMPMEM_RESET SONAME 'ha_innodb_plugin.so';
